export const environment = {
  production: false,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGU5YmQyMC0zZWQ1LTQ1MzMtYTdlZi1iMWYwOWJhNjVkMzgiLCJlbWFpbCI6InRpYWdvQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJUaWFnbyBTYW50aW5pIiwibmJmIjoxNjk2ODY0NzMxLCJleHAiOjE2OTY4OTM1MzEsImlhdCI6MTY5Njg2NDczMSwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.iPvXb-JEVkkJEF6EQvsoCMpKLGPhixMqgTHEPF8kznc',
};
