export const environment = {
  production: true,
  apiKey:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NGU5YmQyMC0zZWQ1LTQ1MzMtYTdlZi1iMWYwOWJhNjVkMzgiLCJlbWFpbCI6InRpYWdvQGdtYWlsLmNvbSIsImdpdmVuX25hbWUiOiJUaWFnbyBTYW50aW5pIiwibmJmIjoxNjk2NTI0NzI2LCJleHAiOjE2OTY1NTM1MjYsImlhdCI6MTY5NjUyNDcyNiwiaXNzIjoiZUFnZW5kYSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3QifQ.BXpnmlyIb9sV3YCT6KwjNYJLpep4FgP9JBYbVbIGfEw',
};
